name: lineder
description: 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # carousel_pro:
  # flare_flutter:
  intl:
  animated_card:
  flutter_slidable:
  firebase_auth: ^0.11.1+1
  cloud_firestore:
  # google_sign_in: ^4.0.1+3
  google_sign_in: ^4.0.7
  shared_preferences:
  # flutter_circular_slider:
  flutter_local_notifications: ^0.7.1+1
  flutter_picker:
  firebase_storage:
  image_picker:
  url_launcher:
  camera:
  package_info:
  firebase_remote_config:
  google_maps_flutter:
  google_maps_webservice:
  geoflutterfire:
  location:
  geolocator:
  flutter_google_places:
  geocoder:
  # flutter_email_sender:
  font_awesome_flutter:
  ntp:
  flutter_calendar:
  cached_network_image: ^0.7.0
  # firebase_messaging: ^4.0.0+1
  firebase_messaging:
  path_provider:
  http: ^0.12.0+1
  async:
  uuid: ^2.0.0
  image_cropper:
  country_code_picker:
  smooth_star_rating:
  cloud_functions:
  firebase_dynamic_links: ^0.4.0+1
  # multi_image_picker:
  # multi_image_picker: ^4.3.3
  # video_player:
  # multi_media_picker: ^0.2.3
  # flutter_image: ^2.0.0 
  shimmer:
  flutter_cupertino_localizations:
  add_2_calendar:
  share:
  flutter_credit_card:
  app_review:
  flutter_offline: ^0.2.4+1
  connectivity: ^0.4.3+6
  # showcaseview: ^0.1.2
  stripe_payment: ^0.2.0
  # flutter_facebook_login: ^3.0.0
  # firebase_analytics:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.7.2+1
  # flutter_icons: ^0.3.0
  #   android: true
  #   ios: true
  #   image_path: "images/lineder.png"
  #   adaptive_icon_background: "images/backg.jpeg"
# dependency_overrides:
    #  flutter_offline: ^0.2.4+1
    #  connectivity: ^0.4.3+6
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - images/lineder.png
  #  - images/backg.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
